env:
  browser: true
  es2021: true
extends:
  - plugin:react/recommended
  - airbnb
  - prettier
  - airbnb-typescript
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
  - 'import'
rules:
  '@typescript-eslint/no-empty-interface':
    - "error"
    - "allowSingleExtends": true
  'import/prefer-default-export': 'off'
  jsx-a11y/label-has-associated-control: 'off'
  '@typescript-eslint/no-misused-promises': 'off'
overrides:
  - files:
      - '*.ts'
      - '*.tsx'

    # As mentioned in the comments, you should extend TypeScript plugins here,
    # instead of extending them outside the `overrides`.
    # If you don't want to extend any rules, you don't need an `extends` attribute.
    extends:
      - 'plugin:@typescript-eslint/recommended'
      - 'plugin:@typescript-eslint/recommended-requiring-type-checking'

    parserOptions:
      project:
        - './tsconfig.json'
