version: '3'
services:
  db:
    restart: always
    image: mariadb:10.7
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "localdatabase"
      MYSQL_USER: "localtest"
      MYSQL_PASSWORD: "localtest"
    ports:
      - "127.0.0.1:20001:3306"
    volumes:
      - ./docker/data/db:/var/lib/mysql
      - ./docker/ddl:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "-u", "root", "-P", "root", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
  redis:
    restart: always
    image: redis:6.2
    ports:
      - "127.0.0.1:20002:6379"
    volumes:
      - ./docker/data/redis:/data
    healthcheck:
      test: ["CMD", "redis-cli", "-h", "localhost", "-p", "6379", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
  nginx:
    restart: always
    image: nginx:1.16.1
    ports:
      - "127.0.0.1:20003:80"
    volumes:
      - ./docker/config/nginx:/etc/nginx/conf.d
    healthcheck:
      test: ["CMD", "nginx", "-t"]
      interval: 10s
      timeout: 5s
      retries: 3
  front:
    restart: always
    build: ./frontend/
    ports:
      - "127.0.0.1:3000:3000"
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:3000/ || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
  backend:
    restart: always
    build: ./backend/
    ports:
      - "127.0.0.1:4000:8080"
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:8080/ || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
