spring:
  main:
    web-application-type: none
    banner-mode: "off"
    lazy-initialization: true
    log-startup-info: false
logging:
  level:
    root: warn
    me:
      pinfort:
        tsvideosmanager: info
