spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/${DATABASE_NAME:localdatabase}
    username: ${DATABASE_USER_NAME:localtest}
    password: ${DATABASE_PASSWORD:localtest}
    validationQuery: SELECT 1
    testOnBorrow: true
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      pool-name: ConnectionPool
      leakDetectionThreshold: 5000
      connection-test-query: SELECT 1
      minimum-idle: 5
      maximum-pool-size: 10
      auto-commit: false
