spring:
  datasource:
    url: ${DATABASE_CONNECTION:jdbc:tc:mariadb:10.7:///?TC_INITSCRIPT=ddl/01_create_database.sql}
    username: ${DATABASE_USER_NAME:test}
    password: ${DATABASE_PASSWORD:test}
    validationQuery: SELECT 1
    testOnBorrow: true
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      pool-name: ConnectionPool
      leakDetectionThreshold: 5000
      connection-test-query: SELECT 1
      minimum-idle: 5
      maximum-pool-size: 10
      auto-commit: false
samba:
  video-store-nas:
    url: ${VIDEO_STORE_NAS_URL:}
    username: ${VIDEO_STORE_NAS_USERNAME:pinfort}
    password: ${VIDEO_STORE_NAS_PASSWORD:password}
