name: backend ci
on: 
  pull_request:
    types: [opened, synchronize, reopened]

defaults:
  run:
    working-directory: backend

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build --no-daemon -x test -x ktlintCheck
      - name: Ktlint
        run: ./gradlew ktlintCheck
      - name: test
        env:
          DATABASE_CONNECTION: jdbc:tc:mariadb:10.7:///?TC_INITSCRIPT=ddl/01_create_database.sql
          DATABASE_USER_NAME: test
          DATABASE_PASSWORD: test
        run: ./gradlew test
