name: backend jar generate
on: 
  pull_request:
    types: [opened, synchronize, reopened]

defaults:
  run:
    working-directory: backend

jobs:
  gen-jar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: bootJar
        run: ./gradlew console:bootJar
      - name: upload jar
        uses: actions/upload-artifact@v3
        with:
          name: ts-videos-manager.jar
          path: backend/console/build/libs/console.jar
          retention-days: 5
